apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: django-project-repo
  namespace: pipeline-project
spec:
  params:
    - name: url
      value: 'https://github.com/richardwalkerdev/tekton-django.git'
    - name: revision
      value: master
  type: git
