apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: django-project-image
  namespace: pipeline-project
spec:
  type: image
  params:
    - name: url
      value: 'image-registry.openshift-image-registry.svc:5000/pipeline-project/wagtail-example-img:latest'
    - name: digest
      value: 
